CREATE DATABASE IF NOT EXISTS website;

USE website;

CREATE TABLE users(
  id INT(11) NOT NULL AUTO_INCREMENT, 
  username VARCHAR(100) NOT NULL, 
  email VARCHAR(100) NOT NULL, 
  password VARCHAR(100) NOT NULL, 
  PRIMARY KEY(id)
);
